### ISSUE TITLE
Return proper error code from build tool

### ISSUE THREAD

**Issue by mpnally** [30x/authsdk#2] opened 2016-07-01 19:29 UTC
Currently, if the build tool gets a 403 from Edge, it return a 401 to the client. I think this is confusing. IMO, 401 should only be returned if the token is missing or invalid. If the problem is that the token does not give access to the resource, a 403 should be returned. Returning the wrong code makes debugging harder—it causes to clients to look in the wrong place for a solution to their problem.

**Comment by jbowen93** [comment] 2016-09-20 17:47
This issue actually isn't in `30x/authsdk` but instead is in `30x/kiln` I believe the misbehaving LOC is https://github.com/30x/kiln/blob/master/pkg/server/server.go#L811
 @noahdietz do you have any more insight on this before I make a fix?

**Comment by whitlockjc** [comment] 2016-09-20 21:20
That code is working as designed because if you're not an org admin, you are forbidden.  But you might be onto something that the problem @mpnally is reporting isn't in `30x/authsdk`.

**Comment by whitlockjc** [comment] 2016-09-20 21:28
When I review the `30x/kiln` code, I don't see a place where this can happen.  In all places a `401` is returned, I think it's valid and is not a result of an Edge call resulting in a `403` first.  @mpnally, do you remember how you reproduced this?

**Comment by whitlockjc** [comment] 2016-09-20 21:30
I think I found what is going on.  `IsOrgAdmin` can itself return a `403` and in that case, we're returning a `401` from `30x/kiln`.  So when `30x/kiln` checks for org admin, it needs to either return the status code from the error or inspect the error and return a `403` if `IsOrgAdmin`'s error is due to a `403`.

I'm going to close this here and reopen in `30x/kiln`.

**Closed as completed by whitlockjc** 2016-09-20 21:30 UTC
